- ros_topic_name: "thruster1/cmd_thrust"
  gz_topic_name: "/model/rov/joint/thruster1_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "thruster2/cmd_thrust"
  gz_topic_name: "/model/rov/joint/thruster2_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "thruster3/cmd_thrust"
  gz_topic_name: "/model/rov/joint/thruster3_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "thruster4/cmd_thrust"
  gz_topic_name: "/model/rov/joint/thruster4_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "thruster5/cmd_thrust"
  gz_topic_name: "/model/rov/joint/thruster5_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "thruster6/cmd_thrust"
  gz_topic_name: "/model/rov/joint/thruster6_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "thruster7/cmd_thrust"
  gz_topic_name: "/model/rov/joint/thruster7_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "thruster8/cmd_thrust"
  gz_topic_name: "/model/rov/joint/thruster8_joint/cmd_thrust"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ  # BIDIRECTIONAL or ROS_TO_GZ
- ros_topic_name: "front_cam"
  gz_topic_name: "/our_camera"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: BIDIRECTIONAL  # BIDIRECTIONAL or ROS_TO_GZ